### ISSUE TITLE
1.14.4 Spigot spamming error

### ISSUE THREAD

**Issue by Veyjinn** [ULTUX/StoneDropPlugin#13] opened 2019-12-28 13:35 UTC
This error pops up every second right after installing the plugin on the server. 

Pastebin:
https://pastebin.com/iEWnGqA9

**Comment by Veyjinn** [comment] 2019-12-28 13:36
Here I add the Pastebin: https://pastebin.com/iEWnGqA9

**Comment by ULTUX** [comment] 2019-12-28 15:42
No errors should be spammed now.
New plugin version is going to be released immediately to github and in a few days to bukkit.org.

**Comment by ULTUX** [comment] 2019-12-28 15:51
Unfortunately if you want to use the plugin now, before official bukkit release you have to disable auto update in config.yml inside Updater folder, because otherwise the plugin is going to download older version as an update.

**Comment by Veyjinn** [comment] 2020-01-08 12:25
Is it actually 1.14.4 compatible? I would love to see it on 1.14.4 running but for now it has no effect. Pozdrowienia z Krzyków!!

**Comment by Ponanoix** [comment] 2020-01-08 14:42
Thanks, this plugin helped me A LOT on my server. You should definetly install it on yours too. Also recommend ULTUX to other people, he deserves that

**Comment by ULTUX** [comment] 2020-01-08 19:48
> Thanks, this plugin helped me A LOT on my server. You should definetly install it on yours too. Also recommend ULTUX to other people, he deserves that

Thanks a lot xd



> Is it actually 1.14.4 compatible? I would love to see it on 1.14.4 running but for now it has no effect. Pozdrowienia z Krzyków!!

Im so sorry, everything now should be working fine! :)

This is a download link to updated version: https://github.com/ULTUX/StoneDropPlugin/releases/tag/1.5.1
**Don't forget to disable auto update in config, because it was not yet pushed to bukkit.org.**

Pozdro, wgl nie wiedzialem że z Polski jesteś xd

**Comment by Veyjinn** [comment] 2020-01-09 01:40
Rip, again spaming error: https://pastebin.com/DmrN7Hc6 

Beside this, when I try to change drop chances in the config, nothing changes 

> Pozdro z Karłowic, wgl nie wiedzialem że z Wroclawia jesteś xd

Noo niezły przypadek xdd jak szukasz collabu na serwer to możesz się moim zainteresować - już od pół roku w wolnym czasie konfiguruję pluginy xD

**Comment by ULTUX** [comment] 2020-01-09 23:31
Ok this is strange, because I wasn’t able to populate your issue.
Try deleting config.yml file in plugin folder. If this doesn’t fix your issue I will try to fix this this weekend.
To make changes in config.yml file, the server/plugin should be disabled/unloaded.

Spoko, jak masz jakieś inne problemy z pluginami to pisz, spróbuje ci pomoc. Mój Discord: ULTUX#4819

**Comment by ULTUX** [comment] 2020-06-21 20:26
Can't reproduce this issue, maybe this was fixed in previous updates, or this was invidual server error.

**Closed by ULTUX** 2020-06-21 20:26 UTC
